# Generated by Django 3.1.4 on 2021-01-19 13:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 15, 45, 408740, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 15, 45, 408740, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 19, 13, 15, 45, 409741, tzinfo=utc)),
        ),
    ]
