# Generated by Django 3.1.4 on 2020-12-15 17:44

from django.db import migrations, models
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podglad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data_rozpoczecia', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('godzina_rozpoczecia', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('godzina_zakonczenia', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('prowadzacy', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
