# Generated by Django 3.1.4 on 2021-01-12 16:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='cyklicznosc',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 12, 16, 0, 49, 348812, tzinfo=utc)),
        ),
    ]
