# Generated by Django 3.1.5 on 2021-03-08 07:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 7, 46, 12, 574791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 7, 46, 12, 574791, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 8, 7, 46, 12, 564790, tzinfo=utc)),
        ),
    ]
