# Generated by Django 3.1.4 on 2021-01-05 22:03

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_employee_institutionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='prowadzacy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='uczniowie',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
