# Generated by Django 3.1.4 on 2020-12-14 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20201213_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Podglad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=200)),
                ('data_rozpoczecia', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('godzina_rozpoczecia', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('godzina_zakonczenia', models.TimeField(blank=True, default=django.utils.timezone.now)),
                ('prowadzacy', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
