# Generated by Django 3.1.4 on 2020-12-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20201215_1849'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('nazwa', models.CharField(max_length=200)),
                ('kategoria', models.CharField(max_length=200)),
                ('profil', models.CharField(max_length=200)),
            ],
        ),
    ]
