# Generated by Django 3.1.4 on 2021-01-13 21:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0002_auto_20210113_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zgloszenie',
            options={'verbose_name_plural': 'Zgloszenia'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 13, 21, 55, 44, 950862, tzinfo=utc)),
        ),
    ]
