# Generated by Django 3.1.4 on 2021-01-14 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0003_auto_20210113_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('nazwa',)},
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 13, 36, 13, 930472, tzinfo=utc)),
        ),
    ]
