# Generated by Django 3.1.4 on 2020-12-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0003_auto_20201215_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='first_name',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
