# Generated by Django 3.1.5 on 2021-03-09 10:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0003_auto_20210308_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 10, 20, 41, 688922, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 10, 20, 41, 686924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 10, 20, 41, 686924, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 9, 10, 20, 41, 676925, tzinfo=utc)),
        ),
    ]
