# Generated by Django 3.1.4 on 2020-12-18 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0004_institution_first_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='first_name',
        ),
    ]
