# Generated by Django 3.1.4 on 2021-03-13 21:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0004_auto_20210309_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 19, 17, 68626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 19, 17, 66628, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 19, 17, 65627, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 19, 17, 56627, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='PasswordChange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_date', models.DateTimeField(default=datetime.datetime(2021, 3, 13, 21, 19, 17, 68626, tzinfo=utc))),
                ('new_password', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'PasswordChange',
            },
        ),
    ]
