# Generated by Django 3.1.4 on 2021-01-06 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0004_employee_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parentid', models.IntegerField(null=True)),
                ('first_name', models.CharField(default=True, max_length=20)),
                ('last_name', models.CharField(default=True, max_length=20)),
                ('age', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='cyklicznosc',
            field=models.IntegerField(null=True),
        ),
    ]
