# Generated by Django 3.1.4 on 2021-01-14 13:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0004_auto_20210114_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={},
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 13, 54, 0, 257689, tzinfo=utc)),
        ),
    ]
