# Generated by Django 3.1.4 on 2021-03-29 16:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0008_auto_20210322_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 24, 44, 157609, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 24, 44, 155608, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 24, 44, 154608, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 29, 16, 24, 44, 145608, tzinfo=utc)),
        ),
    ]
