# Generated by Django 3.1.4 on 2021-01-14 17:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0008_auto_20210114_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 14, 17, 57, 50, 191469, tzinfo=utc)),
        ),
    ]
