# Generated by Django 3.2 on 2021-05-03 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('dziennik', '0010_auto_20210429_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailchange',
            name='change_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 28, 53, 474296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 28, 53, 472301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 28, 53, 472301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 12, 28, 53, 472301, tzinfo=utc)),
        ),
    ]
